const fs = require("fs");
// eslint-disable-next-line
const child_process = require("child_process");
const Job = require("./job.model");
const { NotFoundException } = require("../utils/exceptions");
const logger = require("../utils/logger");
const { convertForR } = require("./utils");

/**
 * Create a new job.
 * @param {object} body
 * @returns
 */
const createJob = async (body, isDemo = true) => {
  // Mongoose API documentation - Model:
  // https://mongoosejs.com/docs/api/model.html

  // If validation fails, the error will handled as 400
  await new Job(body).validate();

  const job = await Job.create(body);

  const jobFolder = `${job.id}`;
  const jobPath = `/app/r/${jobFolder}`;

  const parametersR = convertForR(job);
  logger.info(`R parameters: ${JSON.stringify(parametersR)}`);

  // eslint-disable-next-line
  await fs.promises.mkdir(jobPath);

  // Just passing the job id which is generated by MongoDB:
  // eslint-disable-next-line security/detect-non-literal-fs-filename
  await fs.promises.writeFile(
    `${jobPath}/job_param.json`,
    // Stringify and format it with spaces:
    JSON.stringify(parametersR, null, 2),
    "utf8"
  );

  if (isDemo) {
    // Copy data for demo:
    await fs.promises.copyFile(
      "/app/r/test/aoi.geojson",
      `${jobPath}/aoi.geojson`
    );
    await fs.promises.copyFile(
      "/app/r/test/samplePolygons.geojson",
      `${jobPath}/samplePolygons.geojson`
    );
  }

  // Run R script:
  const script = child_process.spawn("R", [
    "-e",
    'source("/app/r/aoa_script.R")',
    "--args",
    jobFolder,
  ]);

  script.stdout.on("data", (data) => {
    logger.info(`stdout: ${data}`);
  });

  script.stderr.on("data", (data) => {
    logger.info(`stderr: ${data}`);
  });

  script.on("close", (code) => {
    logger.info(`child process exited with code ${code}`);
  });

  return job;
};

/**
 * Get job by id.
 * @param {string} id
 * @returns
 */
const getJob = async (id) => {
  const job = await Job.findById(id);

  if (!job) {
    // Returns the request with a error code (in that case 404) with the given message.
    // They are pre defined exceptions in /src/utils/exceptions.
    throw new NotFoundException("Unable to find job");
  }

  return job;
};

/**
 * Update existing job.
 * @param {object} body
 * @returns
 */
const updateJob = async (body) => {
  await new Job(body).validate();

  const { matchedCount } = await Job.updateOne({ _id: body.id }, body);

  if (matchedCount === 0) {
    throw new NotFoundException("Unable to update unknown job");
  }

  return Job.findOne({ _id: body.id });
};

/**
 * Get all jobs.
 * @returns
 */
const getJobs = async () => {
  const jobs = await Job.find().sort({ created: "desc" });
  return jobs;
};

/**
 * Delete job.
 * @param {string} id
 * @returns
 */
const deleteJob = async (id) => {
  return Job.deleteOne({ _id: id });
};

module.exports = {
  createJob,
  getJob,
  updateJob,
  getJobs,
  deleteJob,
};
